#!/usr/bin/env node

var https = require("https");

let word = process.argv[2];

let responseData = "";

formatList = list =>
{
    str = ""
    list.forEach(element => str += element + ", ");
    return str.substring(0, str.length - 2)
}

let req = https.request(
    {
        hostname: "api.datamuse.com",
        port: 443,
        path: `/words?ml=${word}`,
        method: "GET",
        header: 
            {
                "Content-Type": "application/json"
            }
    },
    (res) => 
    {
        res.setEncoding('utf8');
        
        res.on('data', (chunk) => 
        {
            responseData += chunk;
        });
        
        res.on("end", () =>
        {
            try 
            {
                let data = JSON.parse(responseData);
                data.forEach(def =>
                    {
                        process.stdout.write(`${def.word} `);
                    }
                );
                console.log();
            }
            catch (error) 
            {
                console.log(`${word} could not be found`);
            }
        });
    }
);

req.on("error", (e) => {console.error(e.message);});
req.end();